[package]
name = "feature_clipboard"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "feature_clipboard"
path = "src/lib.rs"

[dependencies]
arboard = "3.4.0"
tracing = "0.1"